# Site settings
title: Giansimone Perrino
email: hello@giansimone.com
description: > #
domain: giansimone.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://giansimone.com

linkedin_username: giansimone
twitter_username: GiansPerrino
github_username: giansimone
researchgate_username: Giansimone-Perrino

# Build settings
markdown: kramdown
