# Site settings
title: Giansimone Perrino
email: g.perrino(at)imperial.ac.uk
description: > #
domain: giansimone.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://giansimone.github.io

twitter_username: GiansPerrino
github_username: giansimone

# Build settings
markdown: kramdown
