# Site settings
title: Giansimone Perrino
email: g <dot> perrino (at) imperial.ac.uk
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "giansimone.github.io" # the base hostname & protocol for your site

twitter_username: GiansPerrino
github_username: giansimone

# Build settings
markdown: kramdown
