# Site settings
title: Giansimone Perrino
email: giansimone@gmail.com
description: > #
domain: giansimone.dev
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://giansimone.dev

linkedin_username: giansimone
twitter_username: GiansPerrino
github_username: giansimone
researchgate_username: Giansimone-Perrino

# Build settings
markdown: kramdown
